# Generated by Django 3.2.4 on 2021-08-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Name'),
        ),
    ]
